### ISSUE TITLE
Tab size defaults to 1 when no indent_size is set and editor.tabSize is set to auto

### ISSUE THREAD

**Issue by resir014** [Microsoft/vscode-editorconfig#10]
I'm not sure if this is intended behaviour with vscode-editorconfig, but as seen on https://github.com/Microsoft/vscode/commit/5da0947edd3598894064ef4738b5941c32c99698#commitcomment-14856269, in some cases, if no `indent_size` value is set and `editor.tabSize` is set to `"auto"` in the VSCode configs, the tab size will default to 1 instead of the default VSCode settings which is 4.

![2015-12-09_02-21-15](https://cloud.githubusercontent.com/assets/5663877/11666494/613fa45c-9e1f-11e5-9514-6bf7dba6773d.png)

**Comment by SamVerschueren** [comment]
@resir014 use the forked plugin https://github.com/editorconfig/editorconfig-vscode. This is fixed in `v0.2.2`.
