### ISSUE TITLE
tab_size is sometimes set wrong

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode-editorconfig#19]
This is my `.editorconfig`

```
root = true

[*]
indent_style = tab
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[{package.json,*.yml}]
indent_style = space
indent_size = 2

[*.md]
trim_trailing_whitespace = false
```

It has some properties that are not yet supported, but it's future proof :).

One thing I noticed is that the `tab_size` is sometimes calculated wrong. My `editor.tabSize` setting is set to `auto`. But when set to `4`, the issue remains. So I use tabs on all my files, except in `package.json` and in all the `.yml` files.

The most basic project structure looks something like this

```
/
 |- package.json
 |- index.js
 |- .editorconfig
```

#### Steps to reproduce

1. Open the project directory
2. Open `index.js
  * The plugin indicates `EditorConfig: Tabs: 4`
3. Open `package.json`
  * The plugin indicates `EditorConfig: Spaces: 2`
4. Open `index.js`
  * The plugin indicates `EditorConfig: Tabs: 2`

As you can see, after opening a file with spaces (2), the `tab_size` is using not being reset to the correct value because my `.editorconfig` file is not specifying the `indent_size` when using tabs.

**Comment by jedmao** [comment]
@SamVerschueren do you think it would be possible to provide a breaking test on the issue in the form of a PR?

**Comment by SamVerschueren** [comment]
At [line 104](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L104) the `insertSpaces` and `tabSize` properties are read from the text editor. 

I open `index.js`

1. The first time that method runs, those properties are set by the settings file of the user (workspace or global).
2. The options are then overridden at [line 117](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L117)
3. I have no `indent_size` specified for `js` files so the default from the settings (4) is used

I open `package.json`

1. The method executes again but this time, it doesn't take the users settings, it takes the options of the texteditor (which are previously overriden)
2. Because `indent_size` is set for `package.json`, it is set working correctly

I navigate back to `index.js`

1. It uses the `textEditor.options` properties, which have the values of the previous run (with an incorrect `indent_size` of 2)
2. Settings are applied to `index.js` with a wrong `indent_size` of 2
