### ISSUE TITLE
applyEditorConfigToTextEditor is executed multiple times

### ISSUE THREAD

**Issue by SamVerschueren** [Microsoft/vscode-editorconfig#21]
When debugging this plugin, I noticed that the [applyEditorConfigToTextEditor](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L90-L118) method is executed multiple times. These are my findings.

When switching to another file, the method is always executed two times. The first time the `textEditor` is pointing to the file being closed, the second time it is pointing to the file being opened. The reason for this is that the [`onDidChangeActiveTextEditor`](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L11-L13) event is fired and the [`onDidOpenTextDocument`](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L37).

When opening a new window where a file is already active, the method even executes 3 times. The first 2 times are caused by the two blocks I pointed to above, the third time is caused because of the [`rebuildConfigMap`](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L52).

Any feedback on this?

**Comment by jedmao** [comment]
What happens if we remove `onDidOpenTextDocument` entirely? Will `onDidChangeActiveTextEditor` still be fired in all scenarios?

I also noticed this in my debugging, but I didn't look into it any further.

**Comment by SamVerschueren** [comment]
I removed [this](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L11-L14) block and the event seemed to fire every time.  

Tested the following scenarios
- Open new window where a file is already active
- Open new window where no file is active (and thus no texteditor) and a file is selected by the user
- Closed the current file (texteditor) and opened another file

Did I miss a scenario?

But maybe @chrisdias or @egamma can answer the question regarding the events. I'm not entirely sure when those events fire and if we can remove [this](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L11-L14) block entirely.

The only scenario where the [applyEditorConfigToTextEditor](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L90-L118) method is fired twice, is when opening a project where a file is already active. The reason is that [line 37](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L37) causes a trigger as well as [line 52](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L52). This only happens once when opening a new project (if a file is active). So I can live with the method being triggered twice. All the other times, triggering the method twice causes a delay which is noticeable when switching from a document with spaces 2 to a document with tabs 4. You can visually see the document switching from indentation 2 to 4. When I remove [this](https://github.com/Microsoft/vscode-editorconfig/blob/master/src/editorConfigMain.ts#L11-L14) block, that's not the case anymore.

**Comment by jedmao** [comment]
Interesting! I would really love to see good examples of covering these scenarios in tests so we have more confidence when making changes like this. Otherwise, I can't say with certainty that you've covered all scenarios, but it sounds like all the same ones I would cover.

**Comment by chrisdias** [comment]
closing per https://github.com/SamVerschueren/vscode-editorconfig/commit/0a76442e1dff86a9417d2fb913e1dee0bd35c04c
