### ISSUE TITLE
indent_size not honoured in Visual Studio Code Insiders

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode-editorconfig#26]
I am running the Visual Studio Code Insiders build. My `.editorconfig` specifies `indent_size = 2`, but this does not appear to be applied in the IDE. This works in the stable build.

**Comment by egamma** [comment]
Did you install the editor config exension in the insider build? The insider and stable build are full separate install that do not share extensions.

**Comment by OliverJAsh** [comment]
Oh yeah, thanks!
