### ISSUE TITLE
Impelment max_line_length

### ISSUE THREAD

**Issue by rdumont** [Microsoft/vscode-editorconfig#27]
A `max_line_length` property would be nice to have, as described in https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#max_line_length.

**Comment by egamma** [comment]
This version of the extension has been deprecated in favor of https://github.com/editorconfig/editorconfig-vscode. Moving the issue

**Comment by egamma** [comment]
This issue was moved to editorconfig/editorconfig-vscode#53
